spring:
  datasource:
    url: jdbc:mysql://localhost:3306/facebook_v2
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or create
    show-sql: true
